version: "3.7"
services:
  app:
    build:
      target: deploy
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    env_file:
      - ./infra/production.env
      - ./infra/deploy.env
    environment:
      - IMAGE_TAG=${IMAGE_TAG}
